language: php

sudo: false

matrix:
    include:
        - php: 7.1
          env: DOCTRINE="2.5.*"
        - php: 7.1
          env: DOCTRINE="2.6.*"
        - php: 7.2
          env: DOCTRINE="2.6.*"
        - php: 7.3
          env: DOCTRINE="2.6.*"
#        - php: 7.4
#          env: DOCTRINE="2.6.*"

before_install:
  - if [ "$DOCTRINE" != "" ]; then composer require --dev --no-update doctrine/orm=$DOCTRINE; fi

install:
  - composer update $COMPOSER_FLAGS --prefer-dist

script: phpunit
